root = "."
tmp_dir = "tmp"

[build] #The build configuration
  bin = "main"
  cmd = "go build -o {{.Output}} {{.Input}}"
  exclude = ["tmp/*", "client/*"] # Specifies the directories to be excluded from monitoring for changes
  include = ["**/*.go"] # Specifies the file patterns to be included for monitoring.
  ignore = ["tmp/*"] #Specifies the files or directories to be ignored when triggering a build.

